import { expect, test } from "@playwright/test";
import { seedProject } from "./project-fixture";

const key = "juben-workbench:projects:v1";
for (const width of [1440, 390]) test(`默认整体调整、预览和保存保留关联与历史版本 ${width}px`, async ({ page }, testInfo) => {
  await page.setViewportSize({ width, height: 900 });
  const base = await seedProject(page, "整体故事调整", true);
  await page.goto(`${base}/stages/blueprint`);
  await page.getByRole("button", { name: "载入演示蓝图", exact: true }).click();
  const panel = page.getByRole("region", { name: "整体故事调整", exact: true });
  await expect(panel).toBeVisible();
  await expect(page.getByLabel("故事简介", { exact: true })).toBeHidden();
  const details = page.getByText("详细结构编辑（按需展开）", { exact: true });
  await expect(details.locator("..")).not.toHaveAttribute("open");
  await page.getByLabel("版本名称", { exact: true }).fill("调整前的蓝图");
  await page.getByRole("button", { name: "建立蓝图版本", exact: true }).click();
  await expect(page.getByRole("button", { name: "查看版本：调整前的蓝图", exact: true })).toBeVisible();
  const before = await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!).projects[0].blueprint, key);
  await panel.getByLabel("整体故事大纲", { exact: true }).fill("整体重新安排：先让角色交换已知经历，再核对证据，最后承担公开的后果。");
  await expect(page.getByRole("region", { name: "蓝图保存与版本", exact: true }).getByText("有未保存修改", { exact: true })).toBeVisible();
  await page.getByLabel("版本名称", { exact: true }).fill("不可建立的未保存版本");
  await expect(page.getByRole("button", { name: "建立蓝图版本", exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "保存蓝图草稿", exact: true })).toBeDisabled();
  await details.click();
  await expect(page.getByLabel("故事简介", { exact: true })).toBeDisabled();
  await expect(page.getByText("整体调整尚未保存，详细编辑暂时只读，避免两份修改相互覆盖。", { exact: true })).toBeVisible();
  await details.click();
  await panel.getByLabel("整体核心真相", { exact: true }).fill("修改后的整体核心真相，所有事件关联仍待重新核对。");
  await panel.getByRole("button", { name: "角色目标与选择", exact: true }).click();
  const name = before.draft.characters[0].name;
  await panel.getByLabel(`${name}的目标`, { exact: true }).fill("主动核对自己的经历并参与最终抉择");
  await panel.getByRole("button", { name: "每轮节奏", exact: true }).click();
  const firstRound = before.draft.rounds[0];
  await panel.getByLabel(`${firstRound.name}计划分钟`, { exact: true }).fill(String(firstRound.minutes + 5));
  await panel.getByRole("button", { name: "预览整体调整", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "修改前后与关联影响", exact: true });
  await expect(dialog.getByRole("heading", { name: "修改前", exact: true })).toBeVisible();
  await expect(dialog.getByRole("heading", { name: "修改后", exact: true })).toBeVisible();
  await expect(dialog).toContainText("角色目标与选择");
  await expect(dialog).toContainText("核心真相改变时核对整个因果链");
  expect(await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!).projects[0].blueprint, key)).toEqual(before);
  await page.screenshot({ path: testInfo.outputPath(`whole-preview-${width}.png`), animations: "disabled" });
  await page.keyboard.press("Escape");
  expect(await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!).projects[0].blueprint, key)).toEqual(before);
  await panel.getByRole("button", { name: "预览整体调整", exact: true }).click();
  await dialog.getByRole("button", { name: "确认保存整体调整", exact: true }).click();
  await expect(dialog).toBeHidden();
  await expect(page.getByRole("button", { name: "建立蓝图版本", exact: true })).toBeEnabled();
  const after = await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!).projects[0].blueprint, key);
  expect(after.draft.characters[0].goal).toBe("主动核对自己的经历并参与最终抉择");
  expect(after.draft.rounds[0].minutes).toBe(firstRound.minutes + 5);
  expect(after.versions).toEqual(before.versions);
  for (const field of ["relationships", "events", "knowledge", "claims", "clues", "triggers", "endings"]) expect(after.draft[field]).toEqual(before.draft[field]);
  expect(after.draft.characters.map((character: { id: string }) => character.id)).toEqual(before.draft.characters.map((character: { id: string }) => character.id));
  await page.reload();
  await expect(panel.getByLabel("整体故事大纲", { exact: true })).toHaveValue(after.draft.premise);
  await expect(page.getByText("草稿与版本不同 · 待建立新版", { exact: true })).toBeVisible();
  await panel.evaluate((node) => node.scrollIntoView({ block: "start" }));
  await page.screenshot({ path: testInfo.outputPath(`whole-story-${width}.png`), fullPage: true, animations: "disabled" });
  await details.click();
  await expect(page.getByLabel("故事简介", { exact: true })).toHaveValue(after.draft.premise);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
