"use client";
import { useEffect, useRef, useState } from "react";
import { checkBlueprint, type BlueprintData } from "@/domain/blueprint";
import type { WorkbenchState } from "@/domain/workbench";
import { changeWorkbench } from "@/services/workbench-store";
import { useResearchDraft } from "../research/common";
import { Textarea } from "../ui/textarea";
import { Input } from "../ui/input";
import { Button } from "../ui/button";
import { ErrorMessage } from "../shared";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "../ui/dialog";

export function StudioBlueprint({ id, state, update, onDirty }: { id: string; state: WorkbenchState; update: (state: WorkbenchState) => void; onDirty: (value: boolean) => void }) {
  const { draft, change: changeDraft, saved } = useResearchDraft(state.blueprint!);
  const originRevision = useRef<number | null>(null);
  function change(next: BlueprintData) { originRevision.current ??= state.revision; changeDraft(next); }
  const [error, setError] = useState<unknown>(null); const [busy, setBusy] = useState(false); const [preview, setPreview] = useState(false);
  const dirty = JSON.stringify(draft) !== JSON.stringify(state.blueprint);
  useEffect(() => { onDirty(dirty); return () => onDirty(false); }, [dirty, onDirty]);
  const disabled = !!state.job || busy;
  async function save() { setBusy(true); setError(null); try { update(await changeWorkbench(id, originRevision.current ?? state.revision, next => { if (next.versions.length >= 20) throw new Error("已保留20份历史，请先整理档案。"); next.versions.push({ revision: next.blueprintRevision, data: next.blueprint! }); next.blueprint = draft; next.blueprintRevision++; })); originRevision.current = null; saved(); setPreview(false); } catch (failure) { setError(failure); } finally { setBusy(false); } }
  const summary = (data: BlueprintData) => `${data.premise}\n\n真相：${data.truth}\n\n${data.characters.map(c => `${c.name}：${c.goal}；关键选择：${c.choice}`).join("\n")}\n\n${data.rounds.map(r => `${r.name} ${r.minutes}分钟：${r.activity}`).join("\n")}`;
  return <div className="main-stack">
    <section className="panel"><div className="panel-title"><h2>整体蓝图</h2><span>{dirty ? "未保存修改" : "已保存"}</span></div><label className="field-label">大纲<Textarea aria-label="大纲" value={draft.premise} rows={6} maxLength={12000} disabled={disabled} onChange={e => change({ ...draft, premise: e.target.value })} /></label><label className="field-label mt-5">真相<Textarea aria-label="真相" value={draft.truth} rows={5} maxLength={12000} disabled={disabled} onChange={e => change({ ...draft, truth: e.target.value })} /></label></section>
    <section className="panel"><h2>角色目标与选择</h2><div className="record-grid mt-4">{draft.characters.map((character, i) => <article className="record-card" key={character.id}><h3>{character.name} · {character.publicIdentity}</h3><label className="field-label mt-3">目标<Textarea aria-label={`${character.name}目标`} maxLength={12000} disabled={disabled} value={character.goal} onChange={e => change({ ...draft, characters: draft.characters.map((c, index) => index === i ? { ...c, goal: e.target.value } : c) })} /></label><label className="field-label mt-3">关键选择<Textarea aria-label={`${character.name}关键选择`} maxLength={12000} disabled={disabled} value={character.choice} onChange={e => change({ ...draft, characters: draft.characters.map((c, index) => index === i ? { ...c, choice: e.target.value } : c) })} /></label><p className="field-hint mt-3">{character.contribution}</p></article>)}</div></section>
    <section className="panel"><h2>每轮节奏</h2><div className="record-list mt-4">{draft.rounds.map((round, i) => <article className="record-card" key={round.id}><h3>{round.name}</h3><label className="field-label mt-3">计划分钟<Input aria-label={`${round.name}分钟`} type="number" min={1} max={1440} value={round.minutes} disabled={disabled} onChange={e => change({ ...draft, rounds: draft.rounds.map((r, index) => index === i ? { ...r, minutes: Number(e.target.value) } : r) })} /></label><label className="field-label mt-3">玩家行动<Textarea aria-label={`${round.name}行动`} maxLength={12000} value={round.activity} disabled={disabled} onChange={e => change({ ...draft, rounds: draft.rounds.map((r, index) => index === i ? { ...r, activity: e.target.value } : r) })} /></label><p className="field-hint">揭示节点：{round.reveal}</p></article>)}</div></section>
    <section className="panel"><h2>关键关系、证据与终局</h2><details className="archive-details mt-3"><summary>事件先后与每轮人物知情</summary><div className="p-4">{draft.events.map(e => <p key={e.id} className="mb-3">{e.time} · {e.location}：{e.action}</p>)}{draft.knowledge.map(k => <p key={k.id} className="mb-3">{draft.characters.find(c => c.id === k.characterId)?.name} · {draft.rounds.find(r => r.id === k.roundId)?.name}：{k.detail}</p>)}</div></details><p className="field-hint mt-3">这些节点影响所有角色的剧本，修改大纲后需要一起核对。</p><details className="archive-details mt-4"><summary>角色之间如何推进故事</summary><div className="p-4">{draft.relationships.map(r => <p className="mb-3" key={r.id}>{draft.characters.find(c => c.id === r.fromId)?.name} ↔ {draft.characters.find(c => c.id === r.toId)?.name}：{r.truth}；{r.consequence}</p>)}</div></details><details className="archive-details mt-3"><summary>必要结论与可获得线索</summary><div className="p-4">{draft.claims.filter(c => c.required).map(c => <p className="mb-3" key={c.id}>{c.statement} — {draft.clues.filter(clue => clue.supports.includes(c.id)).map(clue => `${clue.name}（${clue.access}）`).join("；") || "缺少支持线索"}</p>)}</div></details><details className="archive-details mt-3"><summary>主持触发与终局选择</summary><div className="p-4">{draft.triggers.map(t => <p className="mb-3" key={t.id}>{t.condition} → {t.action}；卡住时：{t.fallback}</p>)}{draft.endings.map(e => <p className="mb-3" key={e.id}>{e.name}：{e.choice} → {e.consequence}</p>)}</div></details></section>
    {dirty && <Button disabled={disabled} onClick={() => setPreview(true)}>预览并保存修改</Button>}{error != null && <ErrorMessage error={error} />}
    <Dialog open={preview} onOpenChange={setPreview}><DialogContent className="sm:max-w-3xl"><DialogTitle>确认整体调整</DialogTitle><DialogDescription>修改可能影响角色信息、线索和主持触发。保存后旧验证失效，需要重新交叉验证。</DialogDescription><div className="comparison-grid"><div><h3>修改前</h3><pre className="text-preview">{summary(state.blueprint!)}</pre></div><div><h3>修改后</h3><pre className="text-preview">{summary(draft)}</pre></div></div><p>字段与关联待核对：{checkBlueprint(draft).length} 项</p><Button disabled={disabled} onClick={() => void save()}>保存调整</Button>{error != null && <ErrorMessage error={error} />}</DialogContent></Dialog>
  </div>;
}
