import { test, expect, type Page } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { seedProject } from "./project-fixture";
import { offlineCapability, prepared, readState, writeState } from "./workbench-fixture";
import { budgetFixture, testQuotes } from "./budget-fixture";
import { reviewBlueprint, reviewCheckpoint, reviewAudit, plannedArtifact } from "../fixtures/studio-review";
import { buildArtifactPlan, artifactPayload, artifactPlanDigest } from "../../src/server/artifact-plan";
import type { BlueprintData } from "../../src/domain/blueprint";
import type { StudioJobView } from "../../src/domain/studio";
import { parseProjectBackup } from "../../src/domain/project-backup";
function modular(blueprint=reviewBlueprint(), saved=3) {
  const plan=buildArtifactPlan(blueprint),checkpoint=reviewCheckpoint();checkpoint.review.blueprint=blueprint;
  checkpoint.review.artifacts=plan.targets.slice(0,saved).map(target=>plannedArtifact(artifactPayload(blueprint,target)));
  checkpoint.generation={planHash:artifactPlanDigest(plan),units:plan.targets.map((t,i)=>({id:t.id,label:t.label,module:t.module,characterId:t.characterId,roundId:t.roundId,state:i<saved?'saved':i===saved?'running':'pending'}))};
  checkpoint.steps=checkpoint.steps.map(s=>({...s,state:s.id==='designGate'?'saved':s.id==='artifacts'?'running':'pending'}));checkpoint.review.reports={designGate:reviewAudit()};return checkpoint;
}
async function setup(page:Page, blueprint:BlueprintData=reviewBlueprint(),saved=3,running=true){
 await offlineCapability(page);const base=await seedProject(page,'模块正文回归'),state=prepared(),checkpoint=modular(blueprint,saved),jobId=crypto.randomUUID();state.blueprint=blueprint;state.review=checkpoint.review;state.reviewBlueprintRevision=1;state.reviewProgress={jobId,blueprintRevision:1,checkpoint};if(running)state.job={jobId,operation:'review',phase:'模块生成',sourceRevision:1,blueprintRevision:1};await writeState(page,base,state);
 const view:StudioJobView={jobId,status:'running',phase:'模块生成',reviewProgress:checkpoint};return{base,state,view};
}
test('240份正文分页按需挂载，末页展开在新进度后保留，六报告及长单元标签窄屏可读',async({page})=>{
 await page.setViewportSize({width:390,height:844});const bp=reviewBlueprint();bp.characters.push({...bp.characters[0],id:'C',name:'第三角色'});bp.rounds=Array.from({length:46},(_,i)=>({...bp.rounds[0],id:`R${i+1}`,name:`第${i+1}轮`}));bp.endings=Array.from({length:3},(_,i)=>({...bp.endings[0],id:`END${i+1}`,name:`终局${i+1}`}));
 const s=await setup(page,bp,240);let view=s.view;view.reviewProgress!.generation!.units[0].label='L'.repeat(500);for(const id of ['designGate','independentA','independentB','mutualA','mutualB','coordinator'] as const)view.reviewProgress!.review.reports[id]=reviewAudit();view.reviewProgress!.revision++;
 await page.route('**/api/studio/status?**',route=>route.fulfill({json:view}));await page.goto(`${s.base}/stages/generation`);const region=page.getByRole('region',{name:'已保存的阶段成果'});await expect(region).toContainText('正文材料 · 240 份');await expect(region.locator('.studio-review-content > details')).toHaveCount(36);await expect(region.locator('pre')).toHaveCount(0);await expect(region.getByText('自造审查意见，不代表真实模型质量',{exact:true})).toHaveCount(0);
 for(let i=0;i<7;i++)await region.getByRole('button',{name:'下一页正文'}).click();await expect(region).toContainText('第 8/8 页');const last=view.reviewProgress!.review.artifacts.at(-1)!;await region.locator('summary').filter({hasText:last.title}).click();await expect(region.locator('pre')).toHaveText(last.content);
 view=structuredClone(view);view.reviewProgress!.revision++;view.reviewProgress!.review.artifacts.at(-1)!.content='更新后末页完整正文仍可读';await expect(region.locator('pre')).toHaveText('更新后末页完整正文仍可读');await expect(region).toContainText('第 8/8 页');
 for(const label of ['蓝图检查','独立检查A','独立检查B','相互核对A','相互核对B','主模型复核'])await region.getByText(`${label} · 已保存报告`,{exact:true}).click();await expect(region.getByText('自造审查意见，不代表真实模型质量',{exact:true})).toHaveCount(6);
 await region.locator('summary').filter({hasText:'正文生成单元：'}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('模块中断保留正文，v3备份往返清两层运行态，新副本只读且不请求模型',async({page})=>{
 const s=await setup(page);let posts=0;page.on('request',r=>{if(r.method()==='POST'&&/\/api\/studio\/(review|analyze|blueprint)$/.test(r.url()))posts++;});
 const failed:StudioJobView={...s.view,status:'failed',phase:'中断',error:{code:'TEST',message:'自造模块中断'}};await page.route('**/api/studio/status?**',route=>route.fulfill({json:failed}));await page.goto(`${s.base}/stages/generation`);await expect(page.getByRole('button',{name:'查看继续费用'})).toBeVisible();await expect(page.getByText('正文生成单元：已保存 3/10',{exact:true})).toBeVisible();await page.reload();expect((await readState(page,s.base)).reviewProgress?.checkpoint.review.artifacts).toHaveLength(3);
 await page.getByRole('button',{name:'备份项目',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('正文生成单元 3/10');const promise=page.waitForEvent('download');await page.getByRole('button',{name:'下载完整项目备份',exact:true}).click();const download=await promise,text=await readFile((await download.path())!,'utf8'),backup=parseProjectBackup(text);
 expect(backup.schemaVersion).toBe(3);const saved=backup.workbench.reviewProgress!;expect(saved.jobId).toBeNull();expect(saved.checkpoint.runId).toBeNull();expect(saved.checkpoint.steps.some(s=>s.state==='running')).toBe(false);expect(saved.checkpoint.generation?.units[3].state).toBe('interrupted');expect(saved.checkpoint.review.artifacts).toEqual(s.view.reviewProgress!.review.artifacts);
 await page.goto('/projects');await page.getByLabel('选择完整项目备份').setInputFiles({name:'自造模块备份.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.getByRole('button',{name:'恢复为新副本',exact:true}).click();await page.getByRole('button',{name:'打开恢复的副本',exact:true}).click();await page.getByRole('navigation',{name:'创作流程'}).getByRole('link',{name:/交叉验证与导出/}).click();await expect(page.getByRole('heading',{name:'备份中的未完成成果',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'查看继续费用'})).toHaveCount(0);await expect(page.getByRole('button',{name:'导出完整档案',exact:true})).toHaveCount(0);expect(posts).toBe(0);
});
test('零余额已保存7个调用单元仍不可继续，全部16个缓存才解锁且取消不外呼',async({page})=>{
 const s=await setup(page,reviewBlueprint(),6,false);let cached=false,posts=0;page.on('request',r=>{if(r.method()==='POST'&&/\/api\/studio\/review$/.test(r.url()))posts++;});
 await page.route('**/api/studio/budget**',route=>{if(route.request().method()!=='POST'||route.request().postDataJSON().action!=='preview')return route.fallback();const body=route.request().postDataJSON();return route.fulfill({json:{projectId:body.projectId,operation:'review',previewId:crypto.randomUUID(),budget:budgetFixture(body.projectId,0),quotes:testQuotes(),callsMax:16,estimateFen:100,checkpoint:{runId:s.view.reviewProgress!.runId,savedUnits:cached?16:7,totalUnits:16,interruptedUnits:0,allCached:cached}}});});
 await page.goto(`${s.base}/stages/generation`);await page.getByRole('button',{name:'查看继续费用'}).click();const dialog=page.getByRole('dialog',{name:'本次创作费用'});await expect(dialog).toContainText('最多 16 次调用');await expect(dialog).toContainText('7/16 个已保存调用单元');await expect(dialog.getByRole('button',{name:'按项目额度开始'})).toBeDisabled();await dialog.getByRole('button',{name:'取消',exact:true}).click();cached=true;await page.getByRole('button',{name:'查看继续费用'}).click();await expect(dialog).toContainText('16/16 个已保存调用单元');await expect(dialog.getByRole('button',{name:'按项目额度开始'})).toBeEnabled();await dialog.getByRole('button',{name:'取消',exact:true}).click();expect(posts).toBe(0);
});
test('两个页面乱序生成进度不回退单元数量与已经展开的正文',async({page,context})=>{
 const s=await setup(page),current=structuredClone(s.view);current.reviewProgress!.revision=9;const plan=buildArtifactPlan(reviewBlueprint());current.reviewProgress!.review.artifacts.push(plannedArtifact(artifactPayload(reviewBlueprint(),plan.targets[3])));current.reviewProgress!.generation!.units[3].state='saved';let release!:()=>void,held=false;
 await page.route('**/api/studio/status?**',async route=>{if(!held){held=true;await new Promise<void>(r=>{release=r;});await route.fulfill({json:s.view});}else await route.fulfill({json:current});});await page.goto(`${s.base}/stages/generation`);await expect.poll(()=>held).toBe(true);const region=page.getByRole('region',{name:'已保存的阶段成果'});await region.locator('.studio-review-content > details summary').first().click();await expect(region.locator('pre')).toHaveCount(1);
 const other=await context.newPage();await offlineCapability(other);await other.route('**/api/studio/status?**',route=>route.fulfill({json:current}));await other.goto(`${s.base}/stages/generation`);await expect(other.getByText('正文生成单元：已保存 4/10',{exact:true})).toBeVisible();await expect(region.getByText('正文生成单元：已保存 4/10',{exact:true})).toBeVisible();
 await page.evaluate(()=>{const original=IDBDatabase.prototype.transaction;Reflect.set(window,'modularWrites',0);IDBDatabase.prototype.transaction=function(...args){const tx=original.apply(this,args);if(args[1]==='readwrite')tx.addEventListener('complete',()=>Reflect.set(window,'modularWrites',Number(Reflect.get(window,'modularWrites'))+1));return tx;};});release();await page.waitForFunction(()=>Number(Reflect.get(window,'modularWrites'))>0);const saved=(await readState(page,s.base)).reviewProgress!.checkpoint;expect(saved.revision).toBe(9);expect(saved.generation!.units.filter(u=>u.state==='saved')).toHaveLength(4);await expect(region.locator('pre')).toHaveCount(1);await other.close();
});
